### ISSUE TITLE
questions about NAS parallel benchmark experiment result

### ISSUE THREAD

**Issue by insoulity** [darchr/gem5art-experiments#56]
Just out of curiosity, are multi core evaluations for NAS benchmarks discussed in https://github.com/darchr/gem5art-experiments/blob/master/results-notebooks/npb-experiments/npb_gem5art.ipynb done with multithreaded enabled? 

I am asking because I just didn't see OMP_NUM_THREAD variable set in anywhere.

Thanks,
Yongkee

**Comment by ayaz91** [comment]
Hi Yongkee,

We rely on the default value of OMP_NUM_THREAD (same as the number of simulated cores).

-Ayaz

**Comment by insoulity** [comment]
Hi Ayaz,

Thanks for the quick response. Could you elaborate what you mean by the default value of OMP_NUM_THREADS? 

At least in my setting, it's set to be 1 by default unless either one has set with setenv or in an application? Could you give me a pointer where it's set to be the number of simulated cores?

Thanks,
Yongkee

**Comment by ayaz91** [comment]
Please, correct me if I am wrong, but, If OMP_NUM_THREADS variable is not set to anything, the OMP runtime forks same number of application threads as the core count of the host, which is what we are relying on here. We change the number of simulated CPU cores through gem5 run scripts.

**Comment by insoulity** [comment]
Oops, you are correct and that's what OpenMP specification describes. I forgot I'd changed openmp runtime on my own including omp_get_num_procs(). 

Thanks a lot for clarification.
