### ISSUE TITLE
Update Linux git repo for boot tests

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5art-experiments#61]
https://github.com/darchr/gem5art-experiments/blob/92d6d9639563e2129007dfc977f85bd4ef274f61/launch-scripts/launch_boot_tests_gem5_20.py#L84

I think that should be https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

**Comment by powerjg** [comment]
cc @takekoputa

**Comment by takekoputa** [comment]
Yes!

**Comment by ayaz91** [comment]
I had, actually, started using the right source in March, but could not fix this in the launch script for boot tests (npb tests launch script has the right verision).
Update in PR: https://github.com/darchr/gem5art-experiments/pull/62.

**Comment by powerjg** [comment]
Thanks! Feel free to close this issue once the pr is merged
