### ISSUE TITLE
fatal error with KVM cpu on gapbs-experiment

### ISSUE THREAD

**Issue by austinharris** [darchr/gem5art-experiments#77]
When I try to run with the configs-gapbs-tests and the kvm cpu I get this fatal error:

`fatal: Number of ISAs (0) assigned to the CPU does not equal number of threads (1).`

I am on gem5 v20.0.0.3 with the 2 KVM patches mentioned in the boot tutorial.

**Comment by powerjg** [comment]
@ayaz91 or @takekoputa, do you remember off the top of your heads how to fix this?

**Comment by austinharris** [comment]
@powerjg I was able to resolve this by adding list() around this map call:
`list(map(lambda c: c.createThreads(), self.cpu))`

I suppose my issues are because gem5art-experiments currently expects python2 gem5?

**Comment by takekoputa** [comment]
Yes, it was due to the scripts haven't been patched to work with python3.
We have updated the scripts on gem5-resources but we haven't updated it
here.

**Comment by austinharris** [comment]
Okay. I'm just getting back into using a newer version of gem5 so I overlooked gem5-resources and started here.

Maybe a note in the readme that the configs are based (copied?) on this repo would be useful.
