### ISSUE TITLE
gem5 does not build with the patch/tag mentioned in README

### ISSUE THREAD

**Issue by rajesh-s** [darchr/gem5art-experiments#78]
Hi,

I'm trying to compile gem5 using the following:

```bash
git clone https://gem5.googlesource.com/public/gem5
cd gem5
git checkout d40f0bc579fb8b10da7181
git remote add darchr https://github.com/darchr/gem5
git fetch darchr
git cherry-pick 6450aaa7ca9e3040fb9eecf69c51a01884ac370c
git cherry-pick 3403665994b55f664f4edfc9074650aaa7ddcd2c
scons build/X86/gem5.opt -j8
```

I encountered the following error first:

```txt
*** Error loading site_init file './site_scons/site_init.py':
  File "./site_scons/site_init.py", line 52
    except SystemExit, e:
```
Upon checking ```site_init.py```, I realised a non-default python version maybe required for scons and used the following invoke command as described [here](http://www.m5sim.org/Using_a_non-default_Python_installation)

```python2.7 `which scons` build/X86/gem5.opt -j8```

I now encounter the following:

```txt
scons: Reading SConscript files ...
ImportError: No module named six:
  File "gem5/SConstruct", line 102:
    from m5.util import compareVersions, readCommand
  File "src/python/m5/util/__init__.py", line 48:
    from . import convert
  File "/gem5/src/python/m5/util/convert.py", line 31:
    import six
```

Not sure if I'm missing something or if this is still a valid method of applying the KVM patches. Thank you for your time.

Thanks,
Rajesh

**Comment by rajesh-s** [comment]
Turned out to be an issue with python six module. 

```pip``` indicated I had it installed
```
pip install six 
Requirement already satisfied: six in venv/lib/python3.8/site-packages (1.16.0)
```
Need to install using ```apt``` to resolve this. [Source](https://stackoverflow.com/a/40759550)

**Comment by rajesh-s** [comment]
Build fails with gcc-9.3

```txt
build/X86/base/inet.hh:355:45: error: taking address of packed member of 'ip_opt' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  355 |     const uint32_t *addext() const { return &opt_data.addext[0]; }
```

Resolved using:
```bash
sudo apt install gcc-8 g++-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
```
Machine configuration:

```txt
$ uname -r 
5.8.0-55-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

gcc-9.3 installed by default
```

**Comment by powerjg** [comment]
I think that the gem5-users mailing list would be a better place to get answers to these questions.

I believe you use the stable branch all GCC versions should work fine. @takekoputa, @ayaz91, @BobbyRBruce, any idea why this error is occuring on this repo?

**Comment by rajesh-s** [comment]
Hi, 

Thank you for the quick response.

Yes, the stable branch v21.0 works on the latest GCC as expected.

The GCC issue was on this specific commit tag

```
git checkout d40f0bc579fb8b10da7181
```

I haven't been able to find a way to apply the KVM patch on the stable v21.0 is the reason I resorted to using the above version. I've initiated this specific aspect on the mailing list today. Subject for reference: "KVM patch for FS mode and PARSEC on gem5-21". 

Once I have more clarity on this, I'll come back and leave a note in the README for future reference


Thank you very much for your time!
Rajesh

**Comment by BobbyRBruce** [comment]
The README for this repo says to do the following:

`git clone https://gem5.googlesource.com/public/gem5
cd gem5
git checkout d40f0bc579fb8b10da7181
scons build/X86/gem5.opt -j8`

That checkout reverts gem5 to some arbitary commit from November 2019, so I'm not surprised there are bugs.

This repo should be updated to work on our stable release.

**Comment by BobbyRBruce** [comment]
Thanks for the info @rajesh-s. We can continue discussion on the mailing list.
